services:
  server:
    build:
      context: ./server
    develop:
      watch:
        - action: sync
          path: .
          target: /server
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      - DATABASE_URL=postresql://postgres:postgres@db:5432/myCurrentDatabase
      - JWT_SECRET=my-jwt-secret
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - psql



  client:
    build:
      context: ./client
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./client/src:/usr/src/client/src
      - ./client/public:/usr/src/client/public

  psql:
    container_name: postgres_container
    image: postgres:15
    restart: always
    command: postgres -c config_file=/postgresql.conf
    environment:
      PGDATA: postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
      DB_USER: user
      DB_PASSWORD: user123
      DB_NAME: user-db
    volumes:
      - ./postgres-db:/postgres-db
      - ./postgresql.conf:/postgresql.conf
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "50m"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rinatgimaev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 10
    ports:
      - "5050:80"
#   db:
#     image: postgres:13-alpine
#     container_name: postgres-db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: myCurrentDatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
# volumes:
#   postgres-data:
